/// Flutter icons Icons_News
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons_News
///      fonts:
///       - asset: fonts/Icons_News.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Icons_News {
  Icons_News._();

  static const _kFontFam = 'Icons_News';
  static const String? _kFontPkg = null;

  static const IconData business = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData entertainment = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData science = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technology = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
